### ISSUE TITLE
What's the status?

### ISSUE THREAD

**Issue by holgersindbaek** [tbalthazar/onesignal-ruby#1]
I'm want to use One Signal, simply to send a notification to a device. Is that possible now with this library? Any chance you can write a short setup guide? Maybe make it into a gem?

**Comment by tbalthazar** [comment]
You can currently:
- add/update device (aka players)
- send notification to a device.

There's a basic example here:
https://github.com/tbalthazar/onesignal-ruby/blob/master/example.rb

I just pushed the gem to Rubygem, so you should be able to install it easily.

**Comment by holgersindbaek** [comment]
Great... thank you very much.
