### ISSUE TITLE
How to implement NotificationCreate using Filters ?

### ISSUE THREAD

**Issue by aweiand** [tbalthazar/onesignal-ruby#14]
I am trying to create a notification using a filter for specific tags.

I tried the implementation below, but that results in 

> http status : 400 - http body : {"errors":["Please include a case-sensitive header of Authorization: Basic

If I use the include_players_ids instead then the notification works well. So the problem is really in my Filters implementation.

Any suggestions ?

```
params = {  app_id: onesignal_app_id,  contents: { en: 'hello player' }, filters: [ {"field": "tag", "key": "test", "relation": "=", "value": "testtagkey"} ]}

response = OneSignal::Notification.create(params: params)

**Error:** 
OneSignal::OneSignalError: Create Notification error - uri: https://onesignal.com/api/v1/notifications params: {:app_id=>"XXXXXX", :contents=>{:en=>"hello player"}, :filters=>[{:field=>"tag", :key=>"test", :relation=>"=", :value=>"testtagkey"}]} - http status : 400 - http body : {"errors":["Please include a case-sensitive header of Authorization: Basic \u003cYOUR-REST-API-KEY-HERE\u003e with a valid REST API key."],"reference":["https://documentation.onesignal.com/docs/accounts-and-keys#section-keys-ids"]}

```

Thanks!

**Comment by aweiand** [comment]
apparently passing 
`opts = { auth_key: Rails.application.secrets.onesignal_rest_api_key }`
to the create method it works....

**Comment by courtsimas** [comment]
or simply declaring `OneSignal::OneSignal.api_key = ENV['ONE_SIGNAL_REST_API_KEY']` with the api key before hand.
