### ISSUE TITLE
What is the status of the gem?

### ISSUE THREAD

**Issue by k0va1** [tbalthazar/onesignal-ruby#16]
Hi! Thank for useful gem! But as I see it hasn't updated since 2016. Is it still working? Thanks

**Comment by sondnm** [comment]
FYI it is still working at the moment but according to the last OneSignal's [change log](https://documentation.onesignal.com/docs/api-changelog#section-june-26-2018), it might not work with some APIs which currently don't enforce `app_id` in the future.

**Comment by tbalthazar** [comment]
I don't have much time/interest to work on it these days, but I'll do my best to review/merge PRs.
