### ISSUE TITLE
SyntaxError using keyword arguments eg: self.http_object(uri:) ruby 1.9.3

### ISSUE THREAD

**Issue by silentdth** [tbalthazar/onesignal-ruby#2]
The error I get when building is:

    SyntaxError: /usr/local/rvm/gems/ruby-1.9.3-p551/gems/one_signal-    
    0.0.6/lib/one_signal/one_signal.rb:3
    7: syntax error, unexpected tLABEL, expecting ')'
        def self.http_object(uri:)

I googled around and found that keyword arguments might not be supported in ruby 1.9.3? https://robots.thoughtbot.com/ruby-2-keyword-arguments

BUT this gem is available to install for 1.9.3. Is that a mistake?

**Comment by tbalthazar** [comment]
You're right, I forgot to specify the required ruby version in the gemspec. I fixed that and pushed a new version.

**Comment by silentdth** [comment]
Thanks Thomas. I ended up calling the one-signal rest API directly, it is
really simple.
