### ISSUE TITLE
Sending notifications from multiple apps

### ISSUE THREAD

**Issue by dhunnapotha** [tbalthazar/onesignal-ruby#7]
Hey @tbalthazar ,  
I need to send notifications to two different one signal apps from a single rails app. From what I understand, we can't achieve it with the current version of the gem. Please confirm. And please let me know if there is any workaround. 

Thanks

**Comment by tbalthazar** [comment]
Hello @dhunnapotha,

You're right that it was not possible to talk to several OneSignal apps with the gem.
But your use case is definitely valid, so I updated the gem to allow you to do that (version 1.2.0 should be live on rubygems.org).

Each method now also accepts an optional `opts` hash that allows you to specify the `user_auth_key`/`api_key` on a per method basis. It allows a ruby app to talk to several different OneSignal apps:

```ruby
app_1_api_key = "fake api key 1"
app_2_api_key = "fake api key 2"

# by default, method calls will use app_1_api_key
OneSignal::OneSignal.api_key = app_1_api_key

# get player with id "123" in app_1
OneSignal::Player.get(id: "123")

# get player with id "456" in app_2
OneSignal::Player.get(id: "123", opts: {auth_key: app_2_api_key})
```

Please let me know if that works for you.

Cheers,
Thomas.

**Comment by dhunnapotha** [comment]
Cool. Thanks for the prompt enhancement. Really helpful  :thumbsup:
