### ISSUE TITLE
525 error: SSL handshake failed

### ISSUE THREAD

**Issue by jamesfzhang** [tbalthazar/onesignal-ruby#8]
I noticed that occasionally, we'd get 525 errors with this gem. It doesn't happen alot, and I can't deduce a pattern. Is there a workaround for this?

**Comment by tbalthazar** [comment]
@jamesfzhang Looks like an error between CloudFlare and the OneSignal servers: https://support.cloudflare.com/hc/en-us/articles/200278659-Error-525-SSL-handshake-failed. It's probably worth contacting the OneSignal support, but without any logs/example I don't know for sure.

**Comment by tbalthazar** [comment]
No feedback, closing.
