### ISSUE TITLE
How can I send adition data?

### ISSUE THREAD

**Issue by hugoerg56** [tbalthazar/onesignal-ruby#9]
From the dashboard in New Messages I can set aditional data, this is posible with this gem?

**Comment by tbalthazar** [comment]
Maybe you're referring to the `data` (https://documentation.onesignal.com/reference#section-attachments) parameter?

**Comment by hugoerg56** [comment]
yes @tbalthazar that is, thanks!

**Comment by flash4484** [comment]
The create method returns a nil response when I add a data parameter. Works without `data`. Am I missing something? Sample params:
```
{:app_id=>"random-key",
 :headings=>{:en=>"This is a title"},
 :contents=>{:en=>"This is a message"},
 :include_player_ids=>["ABCD1234PLAYERID-1"],
 :android_led_color=>"FF00FF00",
 :data=>{:name=>"test", :payload=>"abc"}}
```
